
import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavBar } from "./components";
import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "./components/BootstrapClient";
import "react-toastify/dist/ReactToastify.css";
import { ReactQueryClientProvider } from "./components/ReactQueryClient";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Loja WA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <ReactQueryClientProvider>
             <NavBar />
            <div className="container p-5">  
               {children}
            </div>
            <BootstrapClient />
            <ToastContainer />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
